In [1]:
path_file = "/home/ahmed.bargady/lustre/data_sec-um6p-st-sccs-6sevvl76uja/IDS/ahmed.bargady/datasets/temp/prod/santos_all.csv"

In [2]:
import pandas as pd

/home/ahmed.bargady/.local/lib/python3.8/site-packages/pandas/core/computation/expressions.py:20: UserWarning: Pandas requires version '2.7.3' or newer of 'numexpr' (version '2.7.1' currently installed).
  from pandas.core.computation.check import NUMEXPR_INSTALLED

In [3]:
df = pd.read_csv(path_file, low_memory=False)

In [4]:
df.head(
    
)

,line,content,labels,rules,datetime,timestamp,source,Content,Label
0,0,2022-01-13T14:31:34.934Z intranet-server syste...,NaN,NaN,2022-01-13 14:31:34.934000+00:00,2022-01-13 14:31:34.934,intranet_monitor,<TIMESTAMP> intranet-server system/system.cpu ...,0
1,1,2022-01-13T14:31:43.504Z intranet-server syste...,NaN,NaN,2022-01-13 14:31:43.504000+00:00,2022-01-13 14:31:43.504,intranet_monitor,<TIMESTAMP> intranet-server system/system.cpu ...,0
2,2,2022-01-13T14:32:28.504Z intranet-server syste...,NaN,NaN,2022-01-13 14:32:28.504000+00:00,2022-01-13 14:32:28.504,intranet_monitor,<TIMESTAMP> intranet-server system/system.cpu ...,0
3,3,2022-01-13T14:33:13.504Z intranet-server syste...,NaN,NaN,2022-01-13 14:33:13.504000+00:00,2022-01-13 14:33:13.504,intranet_monitor,<TIMESTAMP> intranet-server system/system.cpu ...,0
4,4,2022-01-13T14:33:58.504Z intranet-server syste...,NaN,NaN,2022-01-13 14:33:58.504000+00:00,2022-01-13 14:33:58.504,intranet_monitor,<TIMESTAMP> intranet-server system/system.cpu ...,0

In [13]:
dfc = df.copy()

In [14]:
dfc.insert(0, 'LineId', None)
dfc['LineId'] = range(1, len(dfc) + 1)
dfc

,LineId,line,content,labels,rules,datetime,timestamp,source,Content,Label
0,1,0,2022-01-13T14:31:34.934Z intranet-server syste...,NaN,NaN,2022-01-13 14:31:34.934000+00:00,2022-01-13 14:31:34.934,intranet_monitor,<TIMESTAMP> intranet-server system/system.cpu ...,0
1,2,1,2022-01-13T14:31:43.504Z intranet-server syste...,NaN,NaN,2022-01-13 14:31:43.504000+00:00,2022-01-13 14:31:43.504,intranet_monitor,<TIMESTAMP> intranet-server system/system.cpu ...,0
2,3,2,2022-01-13T14:32:28.504Z intranet-server syste...,NaN,NaN,2022-01-13 14:32:28.504000+00:00,2022-01-13 14:32:28.504,intranet_monitor,<TIMESTAMP> intranet-server system/system.cpu ...,0
3,4,3,2022-01-13T14:33:13.504Z intranet-server syste...,NaN,NaN,2022-01-13 14:33:13.504000+00:00,2022-01-13 14:33:13.504,intranet_monitor,<TIMESTAMP> intranet-server system/system.cpu ...,0
4,5,4,2022-01-13T14:33:58.504Z intranet-server syste...,NaN,NaN,2022-01-13 14:33:58.504000+00:00,2022-01-13 14:33:58.504,intranet_monitor,<TIMESTAMP> intranet-server system/system.cpu ...,0
...,...,...,...,...,...,...,...,...,...,...
309626,309627,454,2022-01-18T05:40:43.504Z intranet-server syste...,NaN,NaN,2022-01-18 05:40:43.504000+00:00,2022-01-18 05:40:43.504,intranet_monitor,<TIMESTAMP> intranet-server system/system.cpu ...,0
309627,309628,455,2022-01-18T05:41:28.504Z intranet-server syste...,NaN,NaN,2022-01-18 05:41:28.504000+00:00,2022-01-18 05:41:28.504,intranet_monitor,<TIMESTAMP> intranet-server system/system.cpu ...,0
309628,309629,456,2022-01-18T05:42:13.504Z intranet-server syste...,NaN,NaN,2022-01-18 05:42:13.504000+00:00,2022-01-18 05:42:13.504,intranet_monitor,<TIMESTAMP> intranet-server system/system.cpu ...,0
309629,309630,457,2022-01-18T05:42:58.504Z intranet-server syste...,NaN,NaN,2022-01-18 05:42:58.504000+00:00,2022-01-18 05:42:58.504,intranet_monitor,<TIMESTAMP> intranet-server system/system.cpu ...,0
309630,309631,458,2022-01-18T05:43:43.504Z intranet-server syste...,NaN,NaN,2022-01-18 05:43:43.504000+00:00,2022-01-18 05:43:43.504,intranet_monitor,<TIMESTAMP> intranet-server system/system.cpu ...,0

In [ ]:
# sbp.run(["logadu", "parse", file_path, "--parser", "drain"])
!logadu parse /home/ahmed.bargady/lustre/data_sec-um6p-st-sccs-6sevvl76uja/IDS/ahmed.bargady/datasets/temp/prod/santos_all.csv --parser drain

In [2]:
import pandas as pd

In [1]:
_file_path = "/home/ahmed.bargady/lustre/data_sec-um6p-st-sccs-6sevvl76uja/IDS/ahmed.bargady/datasets/temp/prod/drain/shaw_all_structured.csv"

In [3]:
usecols = ['EventId','Label']
df = pd.read_csv(_file_path, usecols=usecols, low_memory=False)

In [4]:
df.head()

   Label   EventId
0      0  b916f507
1      0  b916f507
2      0  b916f507
3      0  b916f507
4      0  b916f507

In [19]:
df.shape

(373866, 2)

In [20]:
codes, uniques = pd.factorize(df['EventId'], sort=True)
len(codes)

373866

In [7]:
uniques

Index(['0056ce95', '011f88b3', '012bf490', '02877adb', '02d62618', '039ff6dd',
       '056a5fe2', '08d1f5f6', '09c93c67', '0c3b33b9',
       ...
       'f5095f7d', 'f65f117b', 'f701d526', 'f8727b21', 'f9eede1b', 'fab02453',
       'fc227a61', 'fd85201c', 'fda02add', 'fdea319d'],
      dtype='object', length=283)

In [8]:
vocab_size = len(uniques)
vocab_size

283

In [9]:
import numpy as np

In [11]:
labels = df['Label'].to_numpy(dtype=np.int8)
labels

array([0, 0, 0, ..., 0, 0, 0], dtype=int8)

In [28]:
windows = np.lib.stride_tricks.sliding_window_view(codes, 5)
windows.shape

(373862, 5)

In [29]:
windows[:5]

array([[207, 207, 207, 207, 207],
       [207, 207, 207, 207, 207],
       [207, 207, 207, 207, 207],
       [207, 207, 207, 207, 207],
       [207, 207, 207, 207, 207]])

In [32]:
windows = windows[:-1]

In [33]:
windows.shape

(373861, 5)

In [34]:
next_events = codes[5:]
next_events.shape

(373861,)

In [35]:
label_windows = np.lib.stride_tricks.sliding_window_view(labels,5)

In [37]:
label_windows.shape

(373862, 5)

In [38]:
label_windows = label_windows[:-1]
label_windows.shape

(373861, 5)

In [39]:
seq_labels = (label_windows.sum(axis=1) > 0).astype(np.int8)
seq_labels.shape

(373861,)

array([0, 0, 0, ..., 0, 0, 0], dtype=int8)

In [ ]:

         # labels: [0, 1, 1, ...]
        del df  # free memory

        if len(codes) <= self.window_size:
            raise ValueError("Not enough events to form a single window.")

        # Vectorized sliding windows
        # windows shape: (N, window_size)
         # windows: (N, window_size) N: is the number of windows
          # shape (N,)
        # Compute window labels: any anomaly inside the window
        label_windows = np.lib.stride_tricks.sliding_window_view(labels, self.window_size)
        seq_labels = (label_windows.sum(axis=1) > 0).astype(np.int8)

        # Align shapes
        assert windows.shape[0] == next_events.shape[0] == seq_labels.shape[0]

In [6]:
_df = pd.read_csv(_file_path, low_memory=False)

In [7]:
_df.head()

,LineId,Content,EventId,EventTemplate,ParameterList
0,1,"line,content,labels,rules,datetime,timestamp,s...",6b1f64cf,"line,content,labels,rules,datetime,timestamp,s...",[]
1,2,"0,2022-01-24T13:30:28.294Z intranet-server sys...",062e62dd,<*> intranet-server system/system.cpu <*> host...,[]
2,3,"1,2022-01-24T13:30:38.304Z intranet-server sys...",062e62dd,<*> intranet-server system/system.cpu <*> host...,[]
3,4,"2,2022-01-24T13:31:23.305Z intranet-server sys...",ef2910eb,<*> intranet-server system/system.cpu <*> host...,[]
4,5,"3,2022-01-24T13:32:08.304Z intranet-server sys...",ef2910eb,<*> intranet-server system/system.cpu <*> host...,[]

In [15]:
!pip install logadu

Defaulting to user installation because normal site-packages is not writeable
Requirement already satisfied: logadu in /srv/lustre01/project/nlp_team-um6p-st-sccs-id7fz1zvotk/IDS/ahmed.bargady/data/github/logs-ad-ultimate/logadu-package (0.2.11)
Requirement already satisfied: click>=7.0 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from logadu) (8.1.8)
Requirement already satisfied: pandas>=1.0 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from logadu) (2.0.3)
Requirement already satisfied: tqdm>=4.0 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from logadu) (4.66.4)
Requirement already satisfied: regex>=2020.0 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from logadu) (2024.5.15)
Requirement already satisfied: numpy>=1.0 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from logadu) (1.24.4)
Requirement already satisfied: torch>=2.3.1 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from logadu) (2.4.1)
Requirement already satisfied: pytorch-lightning>=2.0 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from logadu) (2.4.0)
Requirement already satisfied: torchmetrics>=1.0 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from logadu) (1.5.2)
Requirement already satisfied: scikit-learn>=1.0 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from logadu) (1.3.2)
Requirement already satisfied: gensim>=4.0 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from logadu) (4.3.3)
Requirement already satisfied: wandb>=0.15 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from logadu) (0.21.1)
Requirement already satisfied: joblib>=1.0 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from logadu) (1.4.2)
Requirement already satisfied: transformers>=4.0 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from logadu) (4.42.3)
Requirement already satisfied: sentencepiece>=0.1 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from logadu) (0.2.0)
Requirement already satisfied: pytz>=2020.1 in /srv/software/easybuild/software/Anaconda3/2020.11/lib/python3.8/site-packages (from pandas>=1.0->logadu) (2020.1)
Requirement already satisfied: python-dateutil>=2.8.2 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from pandas>=1.0->logadu) (2.9.0.post0)
Requirement already satisfied: tzdata>=2022.1 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from pandas>=1.0->logadu) (2025.1)
Requirement already satisfied: nvidia-cudnn-cu12==9.1.0.70; platform_system == "Linux" and platform_machine == "x86_64" in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from torch>=2.3.1->logadu) (9.1.0.70)
Requirement already satisfied: sympy in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from torch>=2.3.1->logadu) (1.12.1)
Requirement already satisfied: nvidia-cublas-cu12==12.1.3.1; platform_system == "Linux" and platform_machine == "x86_64" in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from torch>=2.3.1->logadu) (12.1.3.1)
Requirement already satisfied: nvidia-cuda-runtime-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64" in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from torch>=2.3.1->logadu) (12.1.105)
Requirement already satisfied: networkx in /srv/software/easybuild/software/Anaconda3/2020.11/lib/python3.8/site-packages (from torch>=2.3.1->logadu) (2.5)
Requirement already satisfied: typing-extensions>=4.8.0 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from torch>=2.3.1->logadu) (4.12.2)
Requirement already satisfied: nvidia-cufft-cu12==11.0.2.54; platform_system == "Linux" and platform_machine == "x86_64" in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from torch>=2.3.1->logadu) (11.0.2.54)
Requirement already satisfied: nvidia-cusparse-cu12==12.1.0.106; platform_system == "Linux" and platform_machine == "x86_64" in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from torch>=2.3.1->logadu) (12.1.0.106)
Requirement already satisfied: nvidia-cusolver-cu12==11.4.5.107; platform_system == "Linux" and platform_machine == "x86_64" in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from torch>=2.3.1->logadu) (11.4.5.107)
Requirement already satisfied: nvidia-nvtx-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64" in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from torch>=2.3.1->logadu) (12.1.105)
Requirement already satisfied: nvidia-nccl-cu12==2.20.5; platform_system == "Linux" and platform_machine == "x86_64" in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from torch>=2.3.1->logadu) (2.20.5)
Requirement already satisfied: triton==3.0.0; platform_system == "Linux" and platform_machine == "x86_64" and python_version < "3.13" in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from torch>=2.3.1->logadu) (3.0.0)
Requirement already satisfied: fsspec in /srv/software/easybuild/software/Anaconda3/2020.11/lib/python3.8/site-packages (from torch>=2.3.1->logadu) (0.8.3)
Requirement already satisfied: nvidia-cuda-cupti-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64" in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from torch>=2.3.1->logadu) (12.1.105)
Requirement already satisfied: jinja2 in /srv/software/easybuild/software/Anaconda3/2020.11/lib/python3.8/site-packages (from torch>=2.3.1->logadu) (2.11.2)
Requirement already satisfied: nvidia-curand-cu12==10.3.2.106; platform_system == "Linux" and platform_machine == "x86_64" in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from torch>=2.3.1->logadu) (10.3.2.106)
Requirement already satisfied: nvidia-cuda-nvrtc-cu12==12.1.105; platform_system == "Linux" and platform_machine == "x86_64" in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from torch>=2.3.1->logadu) (12.1.105)
Requirement already satisfied: filelock in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from torch>=2.3.1->logadu) (3.16.1)
Requirement already satisfied: packaging>=20.0 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from pytorch-lightning>=2.0->logadu) (25.0)
Requirement already satisfied: PyYAML>=5.4 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from pytorch-lightning>=2.0->logadu) (6.0.2)
Requirement already satisfied: lightning-utilities>=0.10.0 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from pytorch-lightning>=2.0->logadu) (0.11.9)
Requirement already satisfied: scipy>=1.5.0 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from scikit-learn>=1.0->logadu) (1.10.1)
Requirement already satisfied: threadpoolctl>=2.0.0 in /srv/software/easybuild/software/Anaconda3/2020.11/lib/python3.8/site-packages (from scikit-learn>=1.0->logadu) (2.1.0)
Requirement already satisfied: smart-open>=1.8.1 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from gensim>=4.0->logadu) (7.1.0)
Requirement already satisfied: pydantic<3 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from wandb>=0.15->logadu) (2.10.6)
Requirement already satisfied: platformdirs in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from wandb>=0.15->logadu) (4.3.6)
Requirement already satisfied: sentry-sdk>=2.0.0 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from wandb>=0.15->logadu) (2.34.1)
Requirement already satisfied: protobuf!=4.21.0,!=5.28.0,<7,>=3.12.0; python_version < "3.9" and sys_platform == "linux" in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from wandb>=0.15->logadu) (5.29.5)
Requirement already satisfied: eval-type-backport; python_version < "3.10" in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from wandb>=0.15->logadu) (0.2.2)
Requirement already satisfied: requests<3,>=2.0.0 in /srv/software/easybuild/software/Anaconda3/2020.11/lib/python3.8/site-packages (from wandb>=0.15->logadu) (2.24.0)
Requirement already satisfied: gitpython!=3.1.29,>=1.0.0 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from wandb>=0.15->logadu) (3.1.45)
Requirement already satisfied: safetensors>=0.4.1 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from transformers>=4.0->logadu) (0.5.2)
Requirement already satisfied: tokenizers<0.20,>=0.19 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from transformers>=4.0->logadu) (0.19.1)
Requirement already satisfied: huggingface-hub<1.0,>=0.23.2 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from transformers>=4.0->logadu) (0.34.4)
Requirement already satisfied: six>=1.5 in /srv/software/easybuild/software/Anaconda3/2020.11/lib/python3.8/site-packages (from python-dateutil>=2.8.2->pandas>=1.0->logadu) (1.15.0)
Requirement already satisfied: mpmath<1.4.0,>=1.1.0 in /srv/software/easybuild/software/Anaconda3/2020.11/lib/python3.8/site-packages (from sympy->torch>=2.3.1->logadu) (1.1.0)
Requirement already satisfied: decorator>=4.3.0 in /srv/software/easybuild/software/Anaconda3/2020.11/lib/python3.8/site-packages (from networkx->torch>=2.3.1->logadu) (4.4.2)
Requirement already satisfied: nvidia-nvjitlink-cu12 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from nvidia-cusparse-cu12==12.1.0.106; platform_system == "Linux" and platform_machine == "x86_64"->torch>=2.3.1->logadu) (12.9.86)
Requirement already satisfied: MarkupSafe>=0.23 in /srv/software/easybuild/software/Anaconda3/2020.11/lib/python3.8/site-packages (from jinja2->torch>=2.3.1->logadu) (1.1.1)
Requirement already satisfied: setuptools in /srv/software/easybuild/software/Anaconda3/2020.11/lib/python3.8/site-packages (from lightning-utilities>=0.10.0->pytorch-lightning>=2.0->logadu) (50.3.1.post20201107)
Requirement already satisfied: wrapt in /srv/software/easybuild/software/Anaconda3/2020.11/lib/python3.8/site-packages (from smart-open>=1.8.1->gensim>=4.0->logadu) (1.11.2)
Requirement already satisfied: annotated-types>=0.6.0 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from pydantic<3->wandb>=0.15->logadu) (0.7.0)
Requirement already satisfied: pydantic-core==2.27.2 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from pydantic<3->wandb>=0.15->logadu) (2.27.2)
Requirement already satisfied: urllib3>=1.26.11 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from sentry-sdk>=2.0.0->wandb>=0.15->logadu) (2.2.3)
Requirement already satisfied: certifi in /srv/software/easybuild/software/Anaconda3/2020.11/lib/python3.8/site-packages (from sentry-sdk>=2.0.0->wandb>=0.15->logadu) (2020.6.20)
Requirement already satisfied: chardet<4,>=3.0.2 in /srv/software/easybuild/software/Anaconda3/2020.11/lib/python3.8/site-packages (from requests<3,>=2.0.0->wandb>=0.15->logadu) (3.0.4)
Requirement already satisfied: idna<3,>=2.5 in /srv/software/easybuild/software/Anaconda3/2020.11/lib/python3.8/site-packages (from requests<3,>=2.0.0->wandb>=0.15->logadu) (2.10)
Requirement already satisfied: gitdb<5,>=4.0.1 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from gitpython!=3.1.29,>=1.0.0->wandb>=0.15->logadu) (4.0.12)
Requirement already satisfied: hf-xet<2.0.0,>=1.1.3; platform_machine == "x86_64" or platform_machine == "amd64" or platform_machine == "arm64" or platform_machine == "aarch64" in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from huggingface-hub<1.0,>=0.23.2->transformers>=4.0->logadu) (1.1.7)
Requirement already satisfied: smmap<6,>=3.0.1 in /home/ahmed.bargady/.local/lib/python3.8/site-packages (from gitdb<5,>=4.0.1->gitpython!=3.1.29,>=1.0.0->wandb>=0.15->logadu) (5.0.2)